name: My little bit of the web
markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter_opts:
    block:
      line_numbers: false